version: 0.1.{build}

# Build for every push
skip_tags: false
skip_non_tags: false

image: Visual Studio 2015
init:
- git config --global core.autocrlf input
cache:
- src\packages -> **\packages.config
platform: Any CPU
configuration:
- Release
before_build:
- cd src
- nuget restore
build:
  project: src\Mastersign.Tasks.sln
  verbosity: normal
test:
  categories:
    except:
    - Rendering
